# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Climate Maps
email: ethan.nelson@aos.wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  A resource for viewing global distributions of variables that describe
  Earth's climate through the energy and water cycles.
baseurl: "/climate-maps/" # the subpath of your site, e.g. /blog
url: "http://lecuyer.aos.wisc.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

products: [
    ['gpcp', 'Rainfall'],
    ['swcre_toa', 'SW Cloud Forcing TOA'],
    ['lwcre_toa', 'LW Cloud Forcing TOA'],
    ['swcre_sfc', 'SW Cloud Forcing Sfc'],
    ['lwcre_sfc', 'LW Cloud Forcing Sfc']
]
